### ISSUE TITLE
Make mul function

### ISSUE THREAD

**Issue by OPAYA** [kairproject/practice_collaboration#4]
We will make a mul function
```
#input can be any real number
x = 2.0 # real number
y = 1.1 # real number

#body will multiply this two of values.
x * y = 2.2 # output : real number
```
test code
```
assert calc.mul(x, y) == 2.2
```
we will test ten of gugudan examples

**Comment by Curt-Park** [comment]
Why should we test m X n examples?
Do they have different coverages?

**Comment by howtowhy** [comment]
There is two inputs(float) in this module.
It should check two input variables.
so that we considered the two input varying examples as a test set.
Even if the input is a float, the integer is the subset of the domain.

**Comment by Curt-Park** [comment]
@howtowhy The main purpose of unittest is not a performance test but specific test coverage.
Please consider the test cases in the view that I mentioned.

**Comment by OPAYA** [comment]
How about this?
'''
assert mul(2, 3) == 6
assert mul(2, 4) == 8
assert mul(3, 4) == 12
'''

**Comment by Curt-Park** [comment]
Just one test case would be okay.
and the inputs, output should be real values.

**Comment by OPAYA** [comment]
```
assert mul(2, 2.3) == 4.6
```

we deiced a this method.

**Comment by Curt-Park** [comment]
@OPAYA We have made a consensus all the input values will be float type.

**Comment by OPAYA** [comment]
```
assert mul(2.0, 2.3) == 4.6
```
Okkkk

**Comment by Curt-Park** [comment]
@OPAYA Please add the test case and a simple description in the body lines of this issue.

**Comment by OPAYA** [comment]
```
calc = Calculator()
# input can be any real number
x = 2.0
y = 1.1

assert calc.mul(x, y) == 2.2
print ("Passed")
```
Is that right??

**Comment by Curt-Park** [comment]
@OPAYA Looks good. Please add the lines with some description in the body.

**Comment by OPAYA** [comment]
Ok i change the body

**Comment by Curt-Park** [comment]
is this line correct?
> x/*y = 2.2 # output : real number

**Comment by OPAYA** [comment]
No, i change this line

**Comment by Curt-Park** [comment]
1. please don't add the last print line in your real test case.
2. please assign YOURSELVES on this issue.

**Comment by howtowhy** [comment]
`please assign YOURSELVES on this issue.` could I ask this meaning?

**Comment by Curt-Park** [comment]
@howtowhy Check the right upper side. You will find 'Assignees'.

**Comment by OPAYA** [comment]
graeattttt!!!!!!!!

**Comment by Curt-Park** [comment]
Thanks for enduring long conversation. Please set this issue card to **In Progress** status.

**Comment by Curt-Park** [comment]
Thanks for your effort. I made a branch: feat/calculator/mul
Good luck.
