### ISSUE TITLE
Add subtract method "sub" in the class "Calculator"

### ISSUE THREAD

**Issue by kdh0429** [kairproject/practice_collaboration#8]
Make subtract function for calculator.
Takes two float input and returns float output result of subtraction of first input to second input.
Implement 'sub()' in class Calculator, 'calculator.py'.
Test will be in 'test_calculator.py'

like
``` 
cal=Calculator()
float result = cal.sub(float a, float b)  
```

example:
``` 
cal = Calculator()
result =cal.sub(2,2)
assert result ==0 
```

it will pass the test

**Comment by Curt-Park** [comment]
Please remove this duplicate.

**Comment by Curt-Park** [comment]
I closed this issue.
